ads/urls.py
from django.urls import path

from . import views

app_name = 'ads'

urlpatterns = [
    path('', views.adsIndex, name='index'),
]

blog_tutorial/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:blog_id>/', views.detail, name='detail')
]

date/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

import core.views as core

app_name = 'base'

urlpatterns = [
    path('', core.index, name='index'),
    path('intro/', core.intro, name='intro'),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('members/', include('django.contrib.auth.urls')),
    path('archive/', include('archive.urls')),
    path('events/', include('events.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_tutorial/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=100)
    pub_date = models.DateTimeField()
    body = models.TextField()

    def summary(self):
        return self.body[:100]

    def pub_date_short(self):
        return self.pub_date.strftime('%d %e %Y')

    def was_published_recently(self):
        return  timezone.now() > self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    user = models.CharField(max_length=50)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    text = models.TextField(max_length=400)
    pub_date = models.DateTimeField(default=timezone.now)

    def pub_date_short(self):
        return self.pub_date.strftime('%d %e %Y')

blog_tutorial/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog, Comment

# Create your views here.


def index(request):
    blogs = Blog.objects.all()
    context = {
        'all_blogs': blogs
    }
    return render(request, 'blog_tutorial/index.html', context)


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    comments = Comment.objects.filter(blog=blog_id)

    context = {
        'blog': blog,
        'comments': comments
    }

    return render(request, 'blog_tutorial/detail.html', context)

blog_tutorial/templates/blog_tutorial/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>{{ blog.title }}</h1>
        <p>{{ blog.summary }}</p>
        <p> {{ blog.pub_date_pretty }}</p>
    </div>
    <div>
        {% for comment in comments %}
            <span>
                {{ comment.user }}
                {{ comment.text }}
                {{ comment.pub_date }}
            </span>
            <br>
        {% endfor %}
    </div>
</body>
</html>

blog_tutorial/templates/blog_tutorial/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>Forward</h1>
        {% for blog in all_blogs %}
            <a href="{% url 'blog:detail' blog.id %}"><h3>{{ blog.title }}</h3></a>
            <p> {{ blog.summary }}</p>
        {% endfor %}
    </div>
</body>
</html>