ads/urls.py
from django.urls import path

from . import views

app_name = 'ads'

urlpatterns = [
    path('', views.adsIndex, name='index'),
]

date/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

import core.views as core

app_name = 'base'

urlpatterns = [
    path('', core.index, name='index'),
    path('intro/', core.intro, name='intro'),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('members/', include('django.contrib.auth.urls')),
    path('archive/', include('archive.urls')),
    path('events/', include('events.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from django.urls import path, re_path

from . import feed, views

app_name = 'news'

urlpatterns = [
    path('feed/', feed.LatestPosts()),
    # Keep this regex to support legacy usernames that may contain spaces or special characters
    re_path(
        r'author/(?P<author>[\w\s.@\u00C0-\u00FF\u00C5\u00C4\u00D6\u00E5\u00E4\u00F6-]+)/$',
        views.author,
        name='author',
    ),
    path('', views.index, name='index'),
    path('<slug:category>/', views.category_index, name='aa_index'),
    path('articles/<slug:slug>/', views.article, name='detail'),
    path('<slug:category>/<slug:slug>/', views.category_article, name='detail'),
]

news/models.py
import logging

from django_ckeditor_5.fields import CKEditor5Field
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

logger = logging.getLogger('date')

POST_SLUG_MAX_LENGTH = 50


class Category(models.Model):
    name = models.CharField(_('Namn'), max_length=255, blank=False)
    slug = models.SlugField(_('Slug'), unique=True, allow_unicode=False)

    class Meta:
        verbose_name = _('kategori')
        verbose_name_plural = _('kategorier')
        ordering = ('name',)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(_('Titel'), max_length=255, blank=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=_('Kategori'), blank=True, null=True)
    content = CKEditor5Field(_('Innehåll'), blank=True)
    author = models.ForeignKey('members.Member', on_delete=models.CASCADE)
    created_time = models.DateTimeField(_('Skapad'), default=timezone.now)
    published_time = models.DateTimeField(_('Publicerad'), editable=False, null=True, blank=True)
    modified_time = models.DateTimeField(_('Modifierad'), editable=False, null=True, blank=True)
    published = models.BooleanField(_('Publicera'), default=True)
    slug = models.SlugField(_('Slug'), unique=True, allow_unicode=False, max_length=POST_SLUG_MAX_LENGTH)

    class Meta:
        verbose_name = _('nyhet')
        verbose_name_plural = _('nyheter')
        ordering = ('id',)

    def __str__(self):
        return self.title

    def publish(self):
        self.published_time = timezone.now()
        self.published = True
        self.save()

    def unpublish(self):
        self.published = False
        self.save()

    def update(self):
        self.modified_time = timezone.now()
        self.save()

news/forms.py
import logging

from django import forms
from django.utils import timezone

from date.functions import slugify_max
from news import models
from news.models import Post

logger = logging.getLogger('date')


class PostCreationForm(forms.ModelForm):

    user = None

    class Meta:
        model = Post
        fields = (
            'title',
            'category',
            'content',
            'published',
            'slug',
        )

    def save(self, commit=True):
        post = super(PostCreationForm, self).save(commit=False)

        logger.debug("Setting post author to {}".format(self.user))
        if self.user is None:
            return None
        post.author = self.user

        # Generate slug
        post.slug = slugify_max(self.data['slug'], max_length=models.POST_SLUG_MAX_LENGTH)
            
        post.published_time = timezone.now()

        if commit:
            post.update_or_create(pk=post.pk)
        return post


class PostEditForm(forms.ModelForm):

    user = None

    class Meta:
        model = Post
        fields = (
            'title',
            'category',
            'content',
            'published',
            'slug',
        )

    def save(self, commit=True):
        post = super(PostEditForm, self).save(commit=False)
        if self.user is None:
            return None

        post.modified_time = timezone.now()

        if commit:
            post.update_or_create(pk=post.pk)
        return post

date/views.py
import datetime
from itertools import chain

from django.conf import settings
from django.core.cache import cache
from django.shortcuts import redirect, render
from django.utils import timezone
from django.utils import translation

from ads.models import AdUrl
from core.cache_keys import DATE_INDEX_CACHE_KEY, SHORT_VIEW_CACHE_TIMEOUT
from events.models import Event
from news.models import Post
from social.models import IgUrl


def index(request):
    cacheable = request.method == 'GET' and not request.GET
    if cacheable:
        cached = cache.get(DATE_INDEX_CACHE_KEY)
        if cached:
            return cached
    events_old_events_included = (Event.objects.filter(
        published=True,
        event_date_end__gte=(timezone.now() - timezone.timedelta(days=31))).order_by('event_date_start'))
    events = events_old_events_included.filter(
        published=True, event_date_end__gte=timezone.now())
    news = Post.objects.filter(
        published=True, category__isnull=True).reverse()[:3]

    # Show Albins Angels logo if new post in last 10 days
    aa_posts = Post.objects.filter(published=True, category__name="Albins Angels").order_by(
        'published_time').reverse()[:1]  # TODO Remove this hardcoding or move to different function/file
    time_since = timezone.now() - timezone.timedelta(days=10)
    aa_post = ''
    if aa_posts and aa_posts[0].published_time > time_since:
        aa_post = aa_posts[0]

    def calendar_format(all_events):
        """ Format events into a dictionary where keys (dates)
        are mapped to data used by the calendar on the frontend"""
        calendar_events_dict = {}
        for event in all_events:
            event_url = "events/" + event.slug
            # The rest of the "html" field is set on the client side
            # since it includes a time that gets localized on the client-side
            event_dict = {event.event_date_start.strftime("%Y-%m-%d"):
                          {
                "link": event_url,
                "modifier": "calendar-eventday",
                "eventFullDate": event.event_date_start,
                "eventTitle": event.title,
                "html": f"<a class='calendar-eventday-popup' id='calendar_link' href='{event_url}'>"
            }
            }
            calendar_events_dict.update(event_dict)
        return calendar_events_dict

    context = {
        'calendar_events': calendar_format(events_old_events_included),
        'events': events,
        'news': news,
        'news_events': list(chain(events, news)),
        'ads': AdUrl.objects.all(),
        'posts': IgUrl.objects.all(),
        'aa_post': aa_post,  # TODO Remove or rename
    }

    response = render(request, 'date/start.html', context)
    if cacheable:
        cache.set(DATE_INDEX_CACHE_KEY, response, SHORT_VIEW_CACHE_TIMEOUT)
    return response


def language(request, lang):
    if str(lang).lower() == 'fi':
        lang = settings.LANG_FINNISH
    else:
        lang = settings.LANG_SWEDISH
    translation.activate(lang)
    # TODO Replace LANGUAGE_SESSION_KEY with something that works in django 4.0
    # request.session[translation.LANGUAGE_SESSION_KEY] = lang
    origin = request.META.get('HTTP_REFERER')
    return redirect(origin)


def handler404(request, *args, **argv):
    response = render(request, 'core/404.html', {})
    response.status_code = 404
    return response


def handler500(request, *args, **argv):
    response = render(request, 'core/500.html', {})
    response.status_code = 404
    return response

news/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from . import models

LATEST_NEWS_POSTS = 10


def index(request):
    latest_news = models.Post.objects.filter(published=True, category__isnull=True).reverse()
    paginator = Paginator(latest_news, LATEST_NEWS_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)  
    return render(request, 'news/index.html', {'latest_news_items': page_obj})
    

def article(request, slug):
    post = get_object_or_404(models.Post, slug=slug, published=True, category__isnull=True)
    return render(request, 'news/article.html', {'article': post})


def author(request, author):
    articles = models.Post.objects.filter(author__username__exact=author, published=True).order_by('-published_time')
    return render(request, 'news/author.html', {'articles': articles})


def category_index(request, category):
    latest_news = models.Post.objects.filter(published=True, category__slug=category).reverse()
    paginator = Paginator(latest_news, LATEST_NEWS_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)  
    return render(request, 'news/index.html', {'latest_news_items': page_obj})


def category_article(request, category, slug):
    post = get_object_or_404(models.Post, slug=slug, published=True, category__slug=category)
    return render(request, 'news/article.html', {'article': post})

templates/date/news/article.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{{ article.title }}{% endblock %}
{% block content %}
    <head>
        <link rel="stylesheet" href="{% static 'news/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'news/css/article.css' %}">
    </head>
    <div class="container-md container-margin-top min-vh-100 p-1">
        <div class="container-size break-words">
            {% if article.category.name == "Albins Angels" %}
                <div class="aa-img"><img src="{% static 'core/images/albins-angels.png' %}"/></div>
            {% endif %}
            <div class="content overflow-auto">
                <h2>{{ article.title }}</h2>
                <h4 class="author">{% trans "Skriven " %}{{ article.published_time }} {% trans "av" %}
                    <a href="{% url "news:author" article.author %}">
                        {% if article.author.get_full_name != " " %}{{ article.author.get_full_name }}{% else %}
                            {{ article.author }}{% endif %}</a></h4>
                {{ article.content | safe }}
            </div>
        </div>
    </div>
{% endblock %}

templates/date/news/index.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}
{% load cache %}

{% block title %}Nyheter{% endblock %}
{% cache 60 news_index LANGUAGE_CODE %}
{% block content %}
    <head>
        <link rel="stylesheet" href="{% static 'news/css/style.css' %}">
    </head>
    <div class="container-md container-margin-top min-vh-100 p-1">
        <div class="container-size break-words">
            {% if latest_news_items.0.category.name == "Albins Angels" %}
                <div class="aa-img"><img src="{% static 'core/images/albins-angels.png' %}"/></div>
            {% endif %}
            {% for news_item in latest_news_items %}
                <div class="content overflow-auto">
                    <a href="
                    {% if news_item.category %}
                        {% url 'news:detail' news_item.category.slug news_item.slug %}
                    {% else %}
                        {% url 'news:detail' news_item.slug %}
                    {% endif %}
                        ">
                        <h2>{{ news_item.title }}</h2>
                    </a>
                    <h4 class="help-text">{{ news_item.author }}, {{ news_item.published_time }}</h4>
                    <div>
                        {{ news_item.content | safe | truncatewords_html:"50" }}
                    </div>

                    {% if news_item.content|wordcount > 50 %}
                        <a href="
                        {% if news_item.category %}
                            {% url 'news:detail' news_item.category.slug news_item.slug %}
                        {% else %}
                            {% url 'news:detail' news_item.slug %}
                        {% endif %}
                            ">
                            <p class="more-button">{% trans 'Läs mera...' %}</p>
                        </a>
                    {% endif %}
                </div>
                {% empty %}
                    <h4 class="text-center">{% trans "Inga nyheter hittades..." %}</h4>
            {% endfor %}
            {% if latest_news_items.has_other_pages %}
                <div class="center">
                    <div class="pagination">
                        {% if latest_news_items.has_previous %}
                            <a href="?page={{ latest_news_items.previous_page_number }}">&laquo;</a>
                        {% else %}
                            <a class="disabled">&laquo;</a>
                        {% endif %}
                        {% for i in latest_news_items.paginator.page_range %}
                            {% if latest_news_items.number == i %}
                                <a class="active">{{ i }}</a>
                            {% else %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endif %}
                        {% endfor %}
                        {% if latest_news_items.has_next %}
                            <a href="?page={{ latest_news_items.next_page_number }}">&raquo;</a>
                        {% else %}
                            <a class="disabled">&raquo;</a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% endcache %}