ads/urls.py
from django.urls import path

from . import views

app_name = 'ads'

urlpatterns = [
    path('', views.adsIndex, name='index'),
]

date/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

import core.views as core

app_name = 'base'

urlpatterns = [
    path('', core.index, name='index'),
    path('intro/', core.intro, name='intro'),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('members/', include('django.contrib.auth.urls')),
    path('archive/', include('archive.urls')),
    path('events/', include('events.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/urls.py
from django.urls import re_path

from . import feed, views

app_name = 'events'

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^my/$', views.MySignupsView.as_view(), name='my-signups'),
    re_path(r'^edit/(?P<token>[0-9a-f-]+)/$', views.EventEditSignupView.as_view(), name='edit-signup'),
    re_path(r'^(?P<slug>[-\w]+)/$', views.EventDetailView.as_view(), name='detail'),
    re_path(r'^feed$', feed.EventFeed(), name='feed'),
]

news/urls.py
from django.urls import path, re_path

from . import feed, views

app_name = 'news'

urlpatterns = [
    path('feed/', feed.LatestPosts()),
    # Keep this regex to support legacy usernames that may contain spaces or special characters
    re_path(
        r'author/(?P<author>[\w\s.@\u00C0-\u00FF\u00C5\u00C4\u00D6\u00E5\u00E4\u00F6-]+)/$',
        views.author,
        name='author',
    ),
    path('', views.index, name='index'),
    path('<slug:category>/', views.category_index, name='aa_index'),
    path('articles/<slug:slug>/', views.article, name='detail'),
    path('<slug:category>/<slug:slug>/', views.category_article, name='detail'),
]

staticpages/urls.py
from django.urls import re_path

from . import views

app_name = 'staticpages'

urlpatterns = [
    re_path(r'^(?P<slug>[-\w]+)/$', views.StaticPageView.as_view(), name='page'),
]

date/views.py
import datetime
from itertools import chain

from django.conf import settings
from django.core.cache import cache
from django.shortcuts import redirect, render
from django.utils import timezone
from django.utils import translation

from ads.models import AdUrl
from core.cache_keys import DATE_INDEX_CACHE_KEY, SHORT_VIEW_CACHE_TIMEOUT
from events.models import Event
from news.models import Post
from social.models import IgUrl


def index(request):
    cacheable = request.method == 'GET' and not request.GET
    if cacheable:
        cached = cache.get(DATE_INDEX_CACHE_KEY)
        if cached:
            return cached
    events_old_events_included = (Event.objects.filter(
        published=True,
        event_date_end__gte=(timezone.now() - timezone.timedelta(days=31))).order_by('event_date_start'))
    events = events_old_events_included.filter(
        published=True, event_date_end__gte=timezone.now())
    news = Post.objects.filter(
        published=True, category__isnull=True).reverse()[:3]

    # Show Albins Angels logo if new post in last 10 days
    aa_posts = Post.objects.filter(published=True, category__name="Albins Angels").order_by(
        'published_time').reverse()[:1]  # TODO Remove this hardcoding or move to different function/file
    time_since = timezone.now() - timezone.timedelta(days=10)
    aa_post = ''
    if aa_posts and aa_posts[0].published_time > time_since:
        aa_post = aa_posts[0]

    def calendar_format(all_events):
        """ Format events into a dictionary where keys (dates)
        are mapped to data used by the calendar on the frontend"""
        calendar_events_dict = {}
        for event in all_events:
            event_url = "events/" + event.slug
            # The rest of the "html" field is set on the client side
            # since it includes a time that gets localized on the client-side
            event_dict = {event.event_date_start.strftime("%Y-%m-%d"):
                          {
                "link": event_url,
                "modifier": "calendar-eventday",
                "eventFullDate": event.event_date_start,
                "eventTitle": event.title,
                "html": f"<a class='calendar-eventday-popup' id='calendar_link' href='{event_url}'>"
            }
            }
            calendar_events_dict.update(event_dict)
        return calendar_events_dict

    context = {
        'calendar_events': calendar_format(events_old_events_included),
        'events': events,
        'news': news,
        'news_events': list(chain(events, news)),
        'ads': AdUrl.objects.all(),
        'posts': IgUrl.objects.all(),
        'aa_post': aa_post,  # TODO Remove or rename
    }

    response = render(request, 'date/start.html', context)
    if cacheable:
        cache.set(DATE_INDEX_CACHE_KEY, response, SHORT_VIEW_CACHE_TIMEOUT)
    return response


def language(request, lang):
    if str(lang).lower() == 'fi':
        lang = settings.LANG_FINNISH
    else:
        lang = settings.LANG_SWEDISH
    translation.activate(lang)
    # TODO Replace LANGUAGE_SESSION_KEY with something that works in django 4.0
    # request.session[translation.LANGUAGE_SESSION_KEY] = lang
    origin = request.META.get('HTTP_REFERER')
    return redirect(origin)


def handler404(request, *args, **argv):
    response = render(request, 'core/404.html', {})
    response.status_code = 404
    return response


def handler500(request, *args, **argv):
    response = render(request, 'core/500.html', {})
    response.status_code = 404
    return response

date/templates/date/april_start.html
{% extends 'base.html' %}
{% block content %}

    {% load static %}
    {% load i18n %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'date/css/april_homepage.css' %}?{% now "U" %}" type="text/css">
        {% get_current_language as LANGUAGE_CODE %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/157670/jquery.jcarousellite.min.js"></script>
    </head>

    <div class="april-container">
        <div class="april-container-size">
            <div class="april-header">
                <span class="april-bigtext">Kemistklubben</span>
                <br>
                vid Åbo Akademi r.f.
                <br>
                <small style="color: red;">Det har skett ett fel, vänligen meddela styrelsen på kk@abo.fi</small>
                <div style="text-align: right; position: relative; z-index: 1; margin: 9px; color: #000; font-size: 12px;">
                    <a href="/members/login" style="color: #000; text-decoration: underline;">Logga in</a>
                </div>
            </div>
            <div class="april-nav">
                <div class="navbar navbar-expand navbar-light p-0">
                    <ul class="navbar-nav">
                        {% for category in categories %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{category.category_name}}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                {% for page in pages %}
                                    {% if page.category|lower == category.category_name|lower %}
                                        <li><a class="dropdown-item" href="{% url 'staticpages:page' page.slug %}">{{page.title}}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% for page in urls %}
                                    {% if page.category|lower == category.category_name|lower %}
                                        {% if user.is_authenticated and page.url == "/members/login/" %}
                                            <li><a class="dropdown-item" href="/archive/pictures/">Bilder</a></li>
                                            <li><a class="dropdown-item" href="/archive/documents/">Dokument</a></li>
                                            <li><a class="dropdown-item" href="/members/info/">Min profil</a></li>
                                            <li><a class="dropdown-item" href="/members/cert/">Medlemspass</a></li>
                                            <li><a class="dropdown-item" href="/admin/">Admin</a></li>
                                            <li><a class="dropdown-item" href="/members/logout/">Logga ut</a></li>
                                        {% else %}
                                            <li><a class="dropdown-item" href="{{ page.url }}">{{page.title}}</a></li>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="april-content-container">
                <div class="april-main-col">
                    <div class="april-news-container">
                        {% for ne in news%}
                            <div class="april-news-content">
                                <h3 class="april-news-title">{{ ne.title }}</h3>
                                <small class="april-news-date">{{ ne.published_time }}</small>
                                <div class="april-news-text">{{ ne.content|safe|truncatewords_html:"50"}}</div>
                                <a class="april-news-button" href="{% url 'news:detail' ne.slug %}">{% trans 'Läs mera' %}...</a>
                            </div>
                            {% empty %}
                            <h3>{% trans 'inga nyheter hittades' %}...</h3>
                        {% endfor %}
                        <a class="april-more-news" href="/news/">Mera nyheter...</a>
                    </div>
                </div>
                <div class="april-side-col">
                    <div class='box div_style'>
                        <img class='jep' src='https://kemistklubben.abo.fi/images/date.png' alt='Evenemang' width='16' height='16' /> Evenemang 
                    </div>
                    <div class="april-events">
                        {% for ev in events|slice:":4" %}
                            <a href="{% url 'events:detail' ev.slug %}" class="">
                                <strong>{{ ev.title }}</strong>
                            </a>
                        {% empty %}
                            <h6>{% trans 'inga aktiva evenemang hittades' %}...</h6>
                        {% endfor %}
                    </div>
                    <div class="box div_style"><img class="jep" src="https://kemistklubben.abo.fi/images/calendar.png" alt="Händelsekalender" width="16" height="16" /> Kalender</div>
                    <div class="april-calendar-container">
                        <div class="april-calendar-box">
                            <table class="april-calendar">
                                {% autoescape off %}
                                    {{calendar}}
                                {% endautoescape %}
                            </table>
                        </div>
                    </div>
                    <div class="logo-container">
                        <div class="mt-3">Samarbetspartners</div>
                        <div class="carousel-logos">
                            <ul>
                                {%for ad in ads%}
                                <li class="company-logo text-center">
                                    <a href="{{ ad.company_url }}">
                                        <img src="{{ ad.ad_url }}" alt="img">
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="april-footer">
                <div class="lefttext">
                Kemistklubben vid Åbo Akademi r.f.<br />
                Aurum<br />
                Henriksgatan 2<br />
                20500 Åbo<br />
                </div>
                <h6 style="text-align: center; padding-top: 30px; font-size: 10px;">Glad 1 April, önskar DaTe 💚🖤</h6>
                <div class="righttext">
                Kanslitid Må - Ti 12-13<br />
                E-post: kk(at)abo.fi
                </div>
                <div class="clearer"><!-- --></div>
            </div>
        </div>
    </div>
    <script>
        $(".carousel-logos").jCarouselLite({
        circular: true,
        vertical: true,
        auto: 1500,
        speed: 1500,
        pause: true,
        visible: 4
        });
        </script>
{% endblock %}

date/templates/date/date_25.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "DaTe - 25" %}{% endblock %}

{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'date/css/date_25.css' %}">
</head>

<div class="container min-vh-100">
    <div class="container-size">
        <div class="loading-bar">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
            <div class="bar4"></div>
            <div class="bar5"></div>
            <div class="bar-error"><div class="bar-6"></div></div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 col-8">
                {% include 'events/svg/pentalbinsvg.html' %}
            </div>
        </div>

        <div class="main-content mt-4">
            <div class="text-center">
                <h2 class="date metallic"> DaTe</h2>
                <h2 class="age card-shine-effect">25</h2>
                <h2 class="countdown metallic" id="countdown">.</h2>
                <h3 class="start-date metallic">24.2.2024</h3>
            </div>
            {% include 'events/svg/circuitssvg.html' %}
        </div>
    </div>
</div>

<script>
    // Set the date we're counting down to
    var countDownDate = new Date("Feb 24, 2024 00:00:01").getTime();

    // Update the count down every 1 second
    var x = setInterval(function() {

      // Get today's date and time
      var now = new Date().getTime();

      // Find the distance between now and the count down date
      var distance = countDownDate - now;

      // Time calculations for days, hours, minutes and seconds
      var days = Math.floor(distance / (1000 * 60 * 60 * 24));
      var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((distance % (1000 * 60)) / 1000);

      // Display the result in the element with id="countdown"
      document.getElementById("countdown").innerHTML = days + "d " + hours + "h "
      + minutes + "m " + seconds + "s ";

      // If the count down is finished, write some text
      if (distance < 0) {
        clearInterval(x);
        document.getElementById("countdown").innerHTML = "🎊🎊🎊🎊🎊🎊";
      }
    }, 1000);
</script>

{% endblock %}