ads/urls.py
from django.urls import path

from . import views

app_name = 'ads'

urlpatterns = [
    path('', views.adsIndex, name='index'),
]

ctf/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'ctf'
urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('<slug:slug>', login_required(views.DetailView.as_view()), name='detail'),
    path('<slug:ctf_slug>/<slug:flag_slug>', login_required(views.flag), name='flag_detail'),
]

date/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

import core.views as core

app_name = 'base'

urlpatterns = [
    path('', core.index, name='index'),
    path('intro/', core.intro, name='intro'),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('members/', include('django.contrib.auth.urls')),
    path('archive/', include('archive.urls')),
    path('events/', include('events.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ctf/models.py
import logging

from django_ckeditor_5.fields import CKEditor5Field
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from members.models import Member

logger = logging.getLogger('date')

POST_SLUG_MAX_LENGTH = 50


class Ctf(models.Model):
    title = models.CharField(_('Titel'), max_length=255, blank=False)
    content = CKEditor5Field(_('Innehåll'), blank=True)
    start_date = models.DateTimeField(_('Startdatum'), default=now)
    end_date = models.DateTimeField(_('Slutdatum'), default=now)
    pub_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(_('Slug'), unique=True, allow_unicode=False, max_length=POST_SLUG_MAX_LENGTH)
    published = models.BooleanField(_('Publicera'), default=True)

    class Meta:
        verbose_name = _('ctf')
        verbose_name_plural = _('ctf')

    def __str__(self):
        return self.title

    def ctf_is_open(self):
        return now() >= self.start_date

    def ctf_ended(self):
        return now() > self.end_date


class Flag(models.Model):
    # uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    ctf = models.ForeignKey(Ctf, on_delete=models.CASCADE)
    solver = models.ForeignKey(Member, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=200)
    flag = models.CharField(max_length=200)
    solved_date = models.DateTimeField(blank=True, null=True)
    clues = CKEditor5Field(_('Clue'), blank=True)
    slug = models.SlugField(_('Slug'), unique=True, allow_unicode=False, max_length=POST_SLUG_MAX_LENGTH)

    class Meta:
        verbose_name = _('Flag')
        verbose_name_plural = _('Flags')

    def __str__(self):
        return self.title


class Guess(models.Model):
    ctf = models.ForeignKey(Ctf, on_delete=models.CASCADE, verbose_name=_('CTF'))
    user = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name=_('Användare'))
    flag = models.ForeignKey(Flag, on_delete=models.CASCADE, verbose_name=_('Flagga'))
    guess = models.CharField(max_length=200, verbose_name=_('Gissning'))
    correct = models.BooleanField(default=False, verbose_name=_('Korrekt'))
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name=_('Tid'))

    class Meta:
        verbose_name = _('Gissning')
        verbose_name_plural = _('Gissningar')

    def __str__(self):
        return f'{self.ctf.title} - {self.flag.title} - {self.user.username} - {self.guess}'

ctf/forms.py
from django import forms

import logging
logger = logging.getLogger('date')

class FlagForm(forms.Form):
    flag = forms.CharField(label='Insert Flag', max_length=100)

    def __init__(self, *args, **kwargs): 
        super(FlagForm, self).__init__(*args, **kwargs)  
        initial = kwargs.get('initial', {})  
        if initial and initial.get('disable_field'):
            self.fields[initial['disable_field']].disabled = True                
        

ctf/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.http import HttpResponseForbidden

from .forms import FlagForm
from .models import Ctf, Flag, Guess
# Create your views here.

import datetime
import logging
logger = logging.getLogger('date')


class IndexView(generic.ListView):
    template_name = 'ctf/index.html'
    context_object_name = 'latest_ctf_list'


    def get_queryset(self):
        """Return the last five published questions."""
        return Ctf.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Ctf
    template_name = 'ctf/detail.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        flags = Flag.objects.filter(ctf=self.object)
        context['flags'] = flags
        return context


def flag(request, ctf_slug, flag_slug):
    ctf = Ctf.objects.filter(slug=ctf_slug).first()
    ctf_flags = Flag.objects.filter(ctf=ctf)
    flag = Flag.objects.filter(ctf=ctf, slug=flag_slug).first()

    form = FlagForm()
    context = {'ctf': ctf, 'flag': flag, 'form': form}

    if request.session.get("flag_valid", False):
        request.session['flag_valid'] = False
        return form_valid(request, context)
    elif request.session.get("flag_invalid", False):
        request.session['flag_invalid'] = False
        return form_invalid(request, context)

    # Check if user has already solved a flag
    user_solved = False
    for ctf_flag in ctf_flags:
        if ctf_flag.solver and request.user == ctf_flag.solver:
            user_solved = True
            context['user_solved'] = user_solved

    if request.method == 'POST':
        if ctf.ctf_is_open() and ctf.published and (request.user.is_authenticated):
            form = FlagForm(request.POST or None)

            if form.is_valid():
                # Check if a input matches the flag
                flag_input = form.cleaned_data.get('flag')
                correct_bool = False
                if flag_input:
                    logger.info(f'FLAG: {flag.title} USER: {request.user} INPUT: {flag_input}')
                    flag_query = Flag.objects.filter(ctf=ctf, slug=flag_slug, flag=flag_input)

                    if flag_query.exists():
                        flag_instance = flag_query.first()
                        request.session['flag_valid'] = True
                        if user_solved or flag_instance.solver or ctf.ctf_ended():
                            # User has already solved a flag or flag is already solved or ctf has ended
                            Guess.objects.create(ctf=ctf, flag=flag_instance, user=request.user, guess=flag_input,
                                                 correct=True)
                            return redirect(request.path)
                        else:
                            # Flag is correctly guessed for the first time
                            flag_instance.solver = request.user
                            flag_instance.solved_date = datetime.datetime.now()
                            flag_instance.save()
                            logger.info(f'Solver: {flag_instance.solver}')
                            context['flag'] = flag_instance
                            context['solved'] = True
                            Guess.objects.create(ctf=ctf, flag=flag_instance, user=request.user, guess=flag_input,
                                                 correct=True)
                            return redirect(request.path)
                    else:
                        # Guess was incorrect or flag does not match
                        if flag:  # Ensure flag instance is not None before creating Guess
                            Guess.objects.create(ctf=ctf, flag=flag, user=request.user, guess=flag_input, correct=False)
                        else:
                            # Handle the case where no valid flag instance is available
                            # This could log an error, notify the user, etc., depending on desired behavior
                            logger.error("Attempted to create a guess with an invalid flag instance.")

                request.session['flag_invalid'] = True
                return redirect(request.path)

        return HttpResponseForbidden()
    # render non post request
    return render(request, 'ctf/flag_detail.html', context)


def form_valid(request, context):
    logger.info('VALID FLAG')
    context['valid'] = '🎊🎊🎊 Rätt Flag! 🎊🎊🎊'
    return render(request, 'ctf/flag_detail.html', context)


def form_invalid(request, context):
    logger.info('INVALID FLAG')
    context['invalid'] = 'Fel Flag angiven, prova igen.'
    return render(request, 'ctf/flag_detail.html', context)

templates/common/ctf/detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{{ ASSOCIATION_NAME_SHORT }} - CTF{% endblock %}

{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'ctf/css/style.css' %}">
</head>

<div class="container-md min-vh-100 container-margin-top">
    <div class="container-size text-center" style="max-width: 500px;">
        <div class="content">
            <a href="{% url 'ctf:index' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i></a>
            <ul class="list-unstyled">
                {% if ctf.ctf_is_open %}
                    <h4>Flags:</h4>
                    {% for flag in flags %}
                        <li class="m-1">
                            <a href="{% url 'ctf:flag_detail' ctf.slug flag.slug %}">{{ flag.title }}</a>
                            {% if flag.solver %}
                                <i class="fa fa-check" aria-hidden="true"></i>
                            {% endif %}
                        </li>
                    {% endfor %}
                {% endif %}
            </ul>
            <h2 class="header">{{ ctf.title }}</h2>
            <p>{{ ctf.content | safe }}</p>
        </div>
    </div>
</div>

{% endblock %}

templates/common/ctf/flag_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{{ ASSOCIATION_NAME_SHORT }} - CTF{% endblock %}

{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'ctf/css/style.css' %}">
</head>

<div class="container-md min-vh-100 container-margin-top">
    <div class="container-size text-center" style="max-width: 500px;">
        <div class="content">
            {% if ctf.ctf_is_open %}
                <a href="{% url 'ctf:detail' ctf.slug %}"><i class="fa fa-arrow-left" aria-hidden="true"></i></a>
                <h2 class="header">{{ flag.title }}</h2>
                <p>{{ flag.clues | safe }}</p>
                {% if valid %}<p class='valid'>{{ valid }}</p>{% endif %}
                {% if invalid %}<p class='invalid'>{{ invalid }}</p>{% endif %}
                {% if flag.solver or solved %}
                    <p><span class="valid">[SOLVED]</span><br>av: {{ flag.solver }}<br>tid: {{ flag.solved_date|timeuntil:ctf.start_date }}</p>
                {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                            <input type="submit" value="Submit">
                    </form>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/common/ctf/index.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{{ ASSOCIATION_NAME_SHORT }} - CTF{% endblock %}

{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'ctf/css/style.css' %}">
</head>

<div class="container-md min-vh-100 container-margin-top">
    <div class="container-size text-center" style="max-width: 500px;">
        <div class="content">
            <h3><i class="fas fa-flag"></i> {{ ASSOCIATION_NAME_SHORT }} CTF <i class="fas fa-flag"></i></h3>
            {% if latest_ctf_list %}
            <ul class="list-unstyled">
            {% for ctf in latest_ctf_list %}
                {% if ctf.published %}
                <li class="m-1">
                    <a href="{% url 'ctf:detail' ctf.slug %}">{{ ctf.title }}</a>
                </li>
                {% endif %}       
            {% endfor %}
            </ul>
            {% else %}
                <p>No CTF's are available.</p>
        {% endif %}
        </div>
    </div>
</div>

{% endblock %}